task_classifier_agent:
  role: >
    Task Manager Expert
  goal: >
    Classify tasks into categories based on the context and the user's request in this note: {note} and the screenshot is: {screenshot_url}.
    Tasks can only be of 2 types: 
      - Summarize notes: Summarize the notes of the user from the screenshot. Here the user doesn't have any specific instructions with the notes
      - Actions: This is when the user specifies an action to be performed with the screenshot.
  backstory: >
    You are a task manager expert. You have been given a task to classify the tasks into categories based on the context and the user's request.

summarize_notes_agent:
  role: >
    Note Summarizer Expert
  goal: >
    Summarize the notes of the user from the screenshot in this note: {note} and the screenshot is: {screenshot_url}.
    Note:
    {notes}
    Screenshot:
    {screenshot_url}
  backstory: >
    You are a note summarizer expert. You have been given a task to summarize the notes of the user from the screenshot.

action_classifier_agent:
  role: >
    Action Classifier Agent
  goal: >
    Classify the action to be performed with the screenshot in this note: {note} and the screenshot is: {screenshot_url}.
    Action can only be of 3 types: 
      - Research: If the user wants to research something from the screenshot this action should be performed.
      - Reminder: If the user wants to set a reminder for something from the screenshot this action should be performed.
      - Other: If the action is not related to the above 2, then it is of type Other.
  backstory: >
    You are an action classifier expert. You have been given a task to classify the action to be performed with the screenshot.

research_agent:
  role: >
    Research Expert
  goal: >
    Research the screenshot and provide the user with the information in this note: {note} and the screenshot is: {screenshot_url}.
  backstory: >
    You are a research expert. You have been given a task to research the screenshot and provide the user with the information.

reminder_agent:
  role: >
    Reminder Agent
  goal: >
    Set a reminder for the user for the screenshot using the tool provided in this note: {note} and the screenshot is: {screenshot_url}.
    Reminder should have a small note as well explaining what the reminder is for.
    The current time is {current_time}
  backstory: >
    You are a reminder expert. You have been given a task to set a reminder for the user for the screenshot.
    You will use the ReminderTool tool to set a reminder with the provided note and time.
